#!/usr/bin/env bash

# forward errors
set -eu

# get project root directory
PROJECT_DIR="$(dirname -- "$( readlink -f -- "$0"; )";)"

# remove files that are generated by the script
rm -rf deps

# ---------------------------------------------------------------------------- #
#                             install dependencies                             #
# ---------------------------------------------------------------------------- #
mkdir deps

# ------------------------------- install vcpkg ------------------------------ #

# download vcpkg and enter its directory
cd $PROJECT_DIR/deps
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg

# bootstrap vcpkg
./bootstrap-vcpkg.sh --disableMetrics

# install vcpkg dependencies
./vcpkg install

# remove the .git folder to prevent the IDE from recognizing the vcpkg git repository
rm -rf .git
